### ISSUE TITLE
Lifx E27 doesn't support color

### ISSUE THREAD

**Issue by hameerabbasi** [node-lifx/lifx-lan-client#9]
As title.

I'm using [my own branch](https://github.com/hameerabbasi/homebridge-lifx-lan/tree/lifx-lan-client) of `homebridge-lifx-lan` that uses this repo instead of `node-lifx`. But it seems the Lifx E27 doesn't support color.

**Comment by ristomatti** [comment]
@hameerabbasi I've been using this codebase for mainly E27 bulbs for years (and the modifications done on top of prior work `node-lifx` since they were implemented, mostly be me).

Can you reproduce the error with a simple node script using only `lifx-lan-client`? For instance using the [example/interactive-cli.js](https://github.com/node-lifx/lifx-lan-client/blob/master/example/interactive-cli.js) example code?

**Comment by hameerabbasi** [comment]
Then let me ask this: Is the API the same as for the current release of `node-lifx`? That example is self-documenting, I should be able to use it to fix things.

**Comment by ristomatti** [comment]
API is the same. Original test suite runs without issues.

**Comment by ristomatti** [comment]
I just ran the example and works fine for me. I've got 5x E27 Original bulbs (from 3 different generations), 4x E27 Mini Color, 2x GU10 downlight, 3x Z LED strip and Tiles set around the apartment.

**Comment by hameerabbasi** [comment]
The interactive example runs fine for me as well, it seems the homebridge plugin hasn't been updated in a while, and the API HAS changed since then. I'll try to fix it up. 😄

**Comment by ristomatti** [comment]
Maybe it's just the `require` call as the package name has changed? The API has been the same as fsr as I've used it I believe (3+ years).
